global:
  scrape_interval: 60s
  scrape_timeout: 60s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'pfSense'
    static_configs:
      - targets: ['172.16.20.1:9100']
  - job_name: 'Gringotts'
    static_configs:
      - targets: ['172.16.20.5:9100']
  - job_name: 'openWrt-Livingroom'
    static_configs:
      - targets: ['172.16.99.3:9100']
  - job_name: 'openWrt-Utility'
    static_configs:
      - targets: ['172.16.99.4:9100']
  - job_name: 'openWrt-Bed'
    static_configs:
      - targets: ['172.16.99.5:9100']
  - job_name: 'openWrt-Attic'
    static_configs:
      - targets: ['172.16.99.6:9100']
  - job_name: 'telegraf'
    static_configs:
      - targets: ['172.23.0.3:9273']
  - job_name: 'Qbittorrent'
    static_configs:
     - targets: ['172.23.0.8:8000']
  - job_name: 'Mikrotik'
    static_configs:
      - targets: ['172.16.99.2']
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.20.5:9116
