{
 "title": "Order of the Phoenix",
 "tags": [
  "Latency",
  "Gringotts",
  "pfSense"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAN - Gateway",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"WAN-IP\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"WAN-IP\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"WAN-IP\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"WAN-IP\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "pfSense - Firewall",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"172.16.99.1\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"172.16.99.1\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"172.16.99.1\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"172.16.99.1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WAN - Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"172.16.20.1:9100\", device=\"igb0\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"172.16.20.1:9100\", device=\"igb0\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pfSense - CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"172.16.20.1:9100\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "node_memory_wired_bytes{instance=\"172.16.20.1:9100\"} + node_memory_active_bytes{instance=\"172.16.20.1:9100\"}",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "pfSense - Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_exec_software_interrupts_total{instance=\"172.16.20.1:9100\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(node_exec_device_interrupts_total{instance=\"172.16.20.1:9100\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Ping google.com",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"google.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"google.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"google.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"google.com\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ping cloudflare.com",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"cloudflare.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"cloudflare.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"cloudflare.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"cloudflare.com\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ping reddit.com",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"reddit.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"reddit.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"reddit.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"reddit.com\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ping github.com",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"github.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"github.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"github.com\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"github.com\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Mikrotik CRS326", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Mikrotik CRS326",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"172.16.99.2\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"172.16.99.2\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"172.16.99.2\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"172.16.99.2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mikrotik - Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(ifHCInOctets{ifName!=\"sfp-sfpplus1\"}[$__rate_interval])) * 8",
     "legendFormat": "In"
    },
    {
     "expr": "sum by(instance) (-irate(ifHCOutOctets{ifName!=\"sfp-sfpplus1\"}[$__rate_interval])) * 8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Mikrotik - CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrProcessorLoad{instance=\"172.16.99.2\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Mikrotik - Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex=\"65536\",instance=\"172.16.99.2\"} * 100)/(hrStorageSize{hrStorageIndex=\"65536\",instance=\"172.16.99.2\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "AccessPoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "openWrt-Livingroom",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"172.16.99.3\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"172.16.99.3\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"172.16.99.3\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"172.16.99.3\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Livingroom - WiFi 5Ghz",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wifi_station_signal_dbm{ifname=\"phy0-ap0\", instance=\"172.16.99.3:9100\"}",
     "legendFormat": "{{mac}} # {{ifname}}"
    }
   ]
  },
  {
   "title": "Livingroom - CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"172.16.99.3:9100\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Bed - RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"172.16.99.3:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"172.16.99.3:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "openWrt-Bed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"172.16.99.5\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"172.16.99.5\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"172.16.99.5\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"172.16.99.5\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bed - WiFi 5Ghz",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wifi_station_signal_dbm{instance=\"172.16.99.5:9100\"}",
     "legendFormat": "{{mac}} # {{ifname}}"
    }
   ]
  },
  {
   "title": "Bed - CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"172.16.99.5:9100\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed - RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"172.16.99.5:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"172.16.99.5:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "openWrt-Attic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"172.16.99.6\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"172.16.99.6\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"172.16.99.6\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"172.16.99.6\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Attic - WiFi 5Ghz",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wifi_station_signal_dbm{ifname=\"phy0-ap0\", instance=\"172.16.99.6:9100\"}",
     "legendFormat": "{{mac}} # {{ifname}}"
    }
   ]
  },
  {
   "title": "Attic - CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"172.16.99.6:9100\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attic - RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"172.16.99.6:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"172.16.99.6:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "openWrt-Utility",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"172.16.99.4\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"172.16.99.4\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"172.16.99.4\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"172.16.99.4\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wifi Network Quality",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wifi_network_quality{ssid=\"Floo Network 5G\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utility - CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"172.16.99.4:9100\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utility - RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"172.16.99.4:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"172.16.99.4:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dns_query_query_time_ms{rcode=\"NOERROR\", host=\"9b216f136c72\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Gringotts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"172.16.20.5\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_average_response_ms{url=\"172.16.20.5\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"172.16.20.5\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"172.16.20.5\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gringotts - CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"172.16.20.5:9100\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU - Temp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by(chip) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}) / 10",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Gringotts - Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[2m]) + avg_over_time(node_memory_Cached_bytes[2m]) + avg_over_time(node_memory_Buffers_bytes[2m])) / avg_over_time(node_memory_MemTotal_bytes[2m])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gringotts - Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"172.16.20.5:9100\", device=\"enp86s0\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{instance=\"172.16.20.5:9100\", device=\"enp86s0\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}